name: Build and Deploy Python Flask app with Docker

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu VM

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t python-flask-app:${{ github.sha }} .

    # Step 4: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Tag Docker image
    - name: Tag Docker Image
      run: |
        docker tag python-flask-app:${{ github.sha }} mithun704/python-flask-app:latest

    # Step 6: Push Docker image to DockerHub
    - name: Push Docker Image
      run: |
        docker push mithun704/python-flask-app:latest

    # Step 7: Deploy the application to Azure Web App 
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2  
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  
        slot-name: production  # Deployment slot (use 'production' for live deployment)
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}  # Azure publish profile (stored in GitHub Secrets)
        images: mithun704/my-spring-app:latest  # The Docker image to deploy (from DockerHub)